### ISSUE TITLE
Hosting Generalized biffing at SHS GitHub account

### ISSUE THREAD

**Issue by GwendolyneFreddy** [SpellholdStudios/generalized_biffing#1]
Hello!

SHS staff have decided to propose an alternative loading link for mods hosted by SHS. If their authors wish so, they will also be available for download on Spellhold Studios' official GitHub account.
So I'm contacting you to see if you would be willing to offer Generalized Biffing on our GitHub account. If so, it goes without saying that we will grant you full administration rights for this repo.

Cheers

**Comment by vbigiani** [comment]
Yes, you can certainly do so (as I had stated some time after disappearing: http://www.shsforums.net/topic/57480-my-mods-are-up-for-adoption/ ). Do I need to do anything to help you with this?

**Comment by GwendolyneFreddy** [comment]
Thanks a lot!

I guess you want to keep your repo, rather than transferring it. SO I could fork it to SHS account. I will invite you as a member and give you rights for it. 
Every time I create a repo for existing mods, I do my best to keep track of ALL previous versions. Unfortunately, SHS server does not keep them when a mod is updated and I must hunt them among all my old external HDs, and sometimes a few are missing.
So if you have kept all versions, I would appreciate you send me to me.

On another end, I know that some people have released a patch since the last release. I guess it was intended for special game installs (don't remember if it was for new EE games or not). I will check it to decide if it is worth being added to your last release or not.

**Comment by vbigiani** [comment]
For me transferring or forking the repo is the same - I think I did so when I moved my mods over at G3, actually (whichever is easier for maintainers).

I don't think I have any backup of older versions of my mods, unfortunately.

I'll trust your judgment re: the patch that's floating around.

**Comment by GwendolyneFreddy** [comment]
Thanks for being so trustful.
I will ask around to try to find older releases.
I have forked your repo into my personal account and will use it as a basis to update the mod if necessary, then transfer it to SHS account.
I will let you know if the mod has been updated. Or not... ;)

**Comment by GwendolyneFreddy** [comment]
Hello,

Here is the WIP new release: https://github.com/GwendolyneFreddy/generalized_biffing#versions
The main modification is this one: https://github.com/GwendolyneFreddy/generalized_biffing#components

If you do agree with it, I will transfer it to SHS GitHub account and release it as v2.3

**Comment by ALIENQuake** [comment]
@vbigiani @GwendolyneFreddy Much preferred option for Project Infinity would be to move the original repository so if it can happen, do it.

**Comment by vbigiani** [comment]
Everything looks good to me.

Let me know if I need to do anything to move the original repository.

**Comment by ALIENQuake** [comment]
@vbigiani Well, you have to open the "Settings" page, scroll down to the bottom when you see "Danger Zone", select "Transfer ownership", fill two fields and click "I understand, transfer this repository". Then @GwendolyneFreddy will accept the request and repository won't need to be forked.

**Comment by ALIENQuake** [comment]
Generally, since we are speaking about it, I am asking for the 'transfer' of all mod repositories to the SpellholdStudios account.

**Comment by GwendolyneFreddy** [comment]
Valerio, thanks for the feedback.
I guess there is no need for you to transfer the repo.
I will transfer my fork into SHS account.

**Comment by ALIENQuake** [comment]
@GwendolyneFreddy For Project Infinity, there is: forks won't be displayed at the "Download Mods" list. So if Valerio is fine with my request, this is the best way to go.

**Comment by GwendolyneFreddy** [comment]
Argh! Bad news indeed.
Fortunately, it only concerns this mod. So the best way would be that I sent him a PR to merge all my modification, then he trasfers the mod into SHS account? Right?

**Comment by ALIENQuake** [comment]
@GwendolyneFreddy No need to. When he will transfer repo, all forks will be transferred also so after the transfer, you will send PR to https://github.com/SpellholdStudios/generalized_biffing.

**Comment by GwendolyneFreddy** [comment]
Great news!
Then Valerio, the ball is in your court!

**Comment by vbigiani** [comment]
Request sent.

**Comment by GwendolyneFreddy** [comment]
Thanks!
And mod updated from my fork: https://github.com/SpellholdStudios/generalized_biffing/releases
